- hosts: all
  become: true

  vars:
    ferm_enabled: true
    nginx_flavor: 'nginx.org'

  roles:
    - role: debops.core
      tags: [ 'role::core' ]

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences_dependent_list:
        - '{{ nginx_apt_preferences_dependent_list }}'
        - '{{ postgresql_server_apt_preferences_dependent_list }}'

    - role: debops.sshd
      tags: [ 'role::sshd' ]
      sshd__allow_groups: [ 'root', 'admins', 'sshusers', 'sftponly', 'vagrant' ]

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ sshd__ferm__dependent_rules }}'
        - '{{ nginx_ferm_dependent_rules }}'
        - '{{ postgresql_server_ferm_dependent_rules }}'

    - role: debops.postgresql_server
      tags: [ 'role::postgresql_server' ]
      postgresql_server_upstream: true

    - role: debops.postgresql
      tags: [ 'role::postgresql' ]

    - role: debops.php5
      tags: [ 'role::php5' ]

    - role: debops.nginx
      tags: [ 'role::nginx' ]
