- hosts: all
  become: true

  vars:
    ferm_enabled: true
    nginx_flavor: 'nginx.org'
    owncloud_database: 'postgresql'
    owncloud_ldap_enable: false
    owncloud_base_packages:
    - 'owncloud'

  roles:
    - role: debops.core
      tags: [ 'role::core' ]

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences_dependent_list:
        - '{{ nginx_apt_preferences_dependent_list }}'
        - '{{ postgresql_server_apt_preferences_dependent_list }}'

    - role: debops.sshd
      tags: [ 'role::sshd' ]
      sshd__allow_groups: [ 'root', 'admins', 'sshusers', 'sftponly', 'vagrant' ]

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ sshd__ferm__dependent_rules }}'
        - '{{ nginx_ferm_dependent_rules }}'
        - '{{ postgresql_server_ferm_dependent_rules }}'

    - role: debops.postgresql_server
      tags: [ 'role::postgresql_server' ]
      postgresql_server_upstream: true

    - role: debops.postgresql
      tags: [ 'role::postgresql' ]
      postgresql_roles:
        - name: '{{ owncloud_database_name }}' # Separate role is needed when owncloud_database_name != owncloud_database_user
        - name: '{{ owncloud_database_user }}' # Password is not passed directly - it will be read for the file
      postgresql_groups:
        - roles: [ '{{ owncloud_database_user }}' ]
          groups: [ '{{ owncloud_database_name }}' ]
          database: '{{ owncloud_database_name }}'
          enabled: '{{ owncloud_database_name != owncloud_database_user }}'
      postgresql_databases:
        - name: '{{ owncloud_database_name }}'
          owner: '{{ owncloud_database_user }}'
      when: (owncloud_database == 'postgresql')

    - role: debops.php5
      tags: [ 'role::php5' ]
      php5_pools:
        - '{{ owncloud_php5_pool }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx_servers:
        - '{{ owncloud_nginx_server }}'
      nginx_upstreams:
        - '{{ owncloud_nginx_upstream_php5 }}'

    - role: debops.owncloud
      tags: [ 'role::owncloud' ]
