- hosts: all
  become: true

  vars:
    ferm_enabled: true
    nginx_flavor: 'nginx.org'

  roles:
    - role: etckeeper-commit
      etckeeper_commit_message: 'Pre roles etckeeper commit'

    - role: debops.core
      tags: [ 'role::core' ]

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.core etckeeper commit'

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences_dependent_list:
        - '{{ nginx_apt_preferences_dependent_list }}'
        - '{{ postgresql_server_apt_preferences_dependent_list }}'

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.apt_preferences etckeeper commit'

    - role: debops.sshd
      tags: [ 'role::sshd' ]
      sshd__allow_groups: [ 'root', 'admins', 'sshusers', 'sftponly', 'vagrant' ]

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.sshd etckeeper commit'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ sshd__ferm__dependent_rules }}'
        - '{{ nginx_ferm_dependent_rules }}'
        - '{{ postgresql_server_ferm_dependent_rules }}'

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.ferm etckeeper commit'

    - role: debops.postgresql_server
      tags: [ 'role::postgresql_server' ]
      postgresql_server_upstream: true

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.postgresql_server etckeeper commit'

    - role: debops.postgresql
      tags: [ 'role::postgresql' ]

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.postgresql etckeeper commit'

    - role: debops.nginx
      tags: [ 'role::nginx' ]

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.nginx etckeeper commit'

  tasks:
    - name: Install /vagrant/git/etc directory
      tags: etckeeper
      become: true
      file:
        state: directory
        dest: '/vagrant/git/etc'
      when: etckeeper_enabled | bool

    - name: Init git /vagrant/git/etc
      become: true
      command: git init
      args:
        chdir: '/vagrant/git/etc'
        creates: '/vagrant/git/etc/.git'
      ignore_errors: true
      when: etckeeper_enabled | bool

    - name: Git import from /etc to /vagrant/git/etc
      become: true
      shell: "git fetch /etc && git reset --hard FETCH_HEAD"
      args:
        chdir: '/vagrant/git/etc'
      ignore_errors: true
      when: etckeeper_enabled | bool
