- hosts: all
  become: true

  vars:
    ferm_enabled: true

  roles:
    - role: etckeeper-commit
      etckeeper_commit_message: 'Pre roles etckeeper commit'

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]

    - role: debops.sshd
      tags: [ 'role::sshd' ]
      sshd__allow_groups: [ 'root', 'admins', 'sshusers', 'sftponly', 'vagrant' ]

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.sshd etckeeper commit'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm_dependent_rules:
        - '{{ sshd__ferm__dependent_rules }}'

    - role: etckeeper-commit
      etckeeper_commit_message: 'Post debops.ferm etckeeper commit'

  tasks:
    - name: Install /vagrant/git/etc directory
      tags: etckeeper
      become: true
      file:
        state: directory
        dest: '/vagrant/git/etc'
      when: etckeeper_enabled | bool

    - name: Init git /vagrant/git/etc
      become: true
      command: git init
      args:
        chdir: '/vagrant/git/etc'
        creates: '/vagrant/git/etc/.git'
      ignore_errors: true
      when: etckeeper_enabled | bool

    - name: Git import from /etc to /vagrant/git/etc
      become: true
      shell: "git fetch /etc && git reset --hard FETCH_HEAD"
      args:
        chdir: '/vagrant/git/etc'
      ignore_errors: true
      when: etckeeper_enabled | bool
