---
- src: https://github.com/solooboroten/ansible-etckeeper.git
  name: etckeeper

- src: https://github.com/solooboroten/ansible-etckeeper-commit.git
  name: etckeeper-commit

- src: debops.core

- src: https://github.com/debops/ansible-sshd.git
  name: debops.sshd
  version: 0b4aa2d01f0a5b046aa9b54c3b05c5143692f35b

- src: debops.ferm

- src: debops.apt_preferences

- src: https://github.com/debops/ansible-postgresql_server.git
  name: debops.postgresql_server
  version: d79fd108276c564cb98adf78d1d58b53a1afeb56

- src: debops.postgresql

- src: debops.php5

- src: debops.nginx

- src: https://github.com/debops/ansible-owncloud.git
  name: debops.owncloud
  version: 64dff5c7da53494e72e4e914e657622c31e01541
